# -*- coding: utf-8 -*-
"""UI text bundles for Chinese/English switching."""

UI_TEXTS = {
    "en": {
        "page_title": "FlowGuard Conversation System Demo",
        "study_page_title": "UML User Study",
        "header_demo_subtitle": "Left: Structured agent (flowchart-driven) | Right: Live flowchart",
        "header_study_subtitle": "Left: structured task conversation | Right: live UML flowchart",
        "info_button": "Info",
        "info_title_demo": "Interface Guide",
        "info_title_study": "Study Guide",
        "info_demo_1": "Goal: demonstrate the linkage between structured dialogue and the flowchart.",
        "info_demo_2": "Left: structured chat panel showing the conversation and current state.",
        "info_demo_3": "Right: flowchart visualization with real-time path and state updates.",
        "info_demo_4": "You can click flowchart nodes to jump and focus.",
        "info_study_1": "Complete tasks in order. Only one task is shown at a time.",
        "info_study_2": "Left: task conversation and progress. Right: live UML flowchart.",
        "info_study_3": "The next task starts automatically 10 seconds after completion.",
        "login_button": "Login",
        "reset_button": "Reset conversation",
        "translate_button": "中文",
        "translate_button_zh": "中文",
        "translate_button_en": "English",
        "not_logged_in": "Not logged in",
        "login_modal_title": "Login",
        "login_modal_user": "Username",
        "login_modal_pass": "Password",
        "login_modal_submit": "Login",
        "login_modal_cancel": "Cancel",
        "study_login_title": "Participant Login",
        "study_login_desc": "Please enter the username and password provided by the researcher.",
        "study_login_submit": "Sign In",
        "study_info_title": "Info",
        "study_info_flow_title": "Flow",
        "study_info_flow_body": "You will complete all configured UML tasks in sequence. Each task ends when any stop node is reached.",
        "study_info_timing_title": "Timing",
        "study_info_timing_body": "After a task is completed, the next task starts automatically after 10 seconds.",
        "study_info_notes_title": "Notes",
        "study_info_notes_1": "Use the assigned account",
        "study_info_notes_2": "Complete tasks in order",
        "study_info_notes_3": "Interactions are recorded for the study",
        "structured_agent_title": "Structured Agent (Flowchart-driven)",
        "structured_agent_subtitle": "Strict flow constraints • Predictable path • Visible state",
        "current_state": "Current State",
        "task_progress": "Task Progress",
        "study_task_jump_label": "Task Switch",
        "study_task_jump_hint": "Auto-advance still works after completion. You can also jump to another task here.",
        "task_target_select_placeholder": "Select target node",
        "task_target_select_hint_pending": "Before answering, scroll the flowchart on the right with your mouse and choose the node you want to reach.",
        "task_target_select_hint_ready": "Target selected: {goal}. You can start answering now.",
        "task_target_select_hint_missing": "Please select a target node in Task Progress before answering.",
        "task_target_select_label": "Target Node",
        "task_awaiting_login": "Awaiting login",
        "task_signin_hint": "Sign in to begin the study.",
        "flowchart_panel_title": "Live Flowchart",
        "flowchart_panel_subtitle": "Visualize states and paths",
        "workflow_select_label": "Workflow",
        "workflow_select_placeholder": "Select a workflow",
        "workflow_select_empty": "No workflows",
        "default_flowchart_title": "Taobao Goods Return Flowchart",
        "send_button": "Send",
        "structured_input_study_placeholder": "Sign in to start...",
        "structured_input_default_placeholder": "Type your message...",
        "structured_input_active_placeholder": "Type your message...",
        "demo_welcome": "You will now start a conversation with the structured agent. The agent will strictly follow the flowchart and update its current state accordingly. Try sending messages to see how it responds based on the defined workflow!",
        "study_welcome": "Sign in to begin the study. One UML task will be shown at a time.",
        "study_task_loaded_prefix": "Task loaded",
        "study_task_loaded_suffix": "Follow the flowchart and complete the task. Reach any stop node to finish.",
        "study_task_loading": "Loading tasks...",
        "study_task_wait": "Please wait.",
        "study_no_tasks": "No tasks",
        "study_no_tasks_desc": "No study tasks are available for this account.",
        "study_task_in_progress": "In progress",
        "study_task_loading_uml": "Loading UML task...",
        "study_task_complete_title": "Task {n} completed",
        "study_task_complete_wait": "Next task starts in {n} seconds.",
        "study_next_task_button": "Go To Next Task",
        "study_done_title": "Thank you for participating",
        "study_done_body": "All tasks are completed. You may close this page.",
        "study_all_done_card_title": "All tasks completed",
        "study_all_done_card_status": "Thank you for participating.",
        "logged_in_as": "Logged in as {username}",
        "login_failed": "Login failed: {error}",
        "load_failed": "Load failed: {error}",
        "task_list_failed": "Task list failed: {error}",
        "task_start_failed": "Task start failed: {error}",
        "task_start_failed_inline": "Unable to start task: {error}",
        "chat_failed": "Sorry, the service is temporarily unavailable. Please try again later.",
        "processing_placeholder": "Processing...",
        "confirm_phrase_1": "Just a quick heads-up: please confirm and we'll move on.",
        "confirm_phrase_2": "This step only needs your confirmation. Please confirm to proceed.",
        "confirm_phrase_3": "Please take a moment to confirm so we can continue.",
        "confirm_phrase_4": "Just confirming with you. Once you confirm, we'll proceed.",
    },
    "zh": {
        "page_title": "FlowGuard 对话系统演示",
        "study_page_title": "UML 用户调研",
        "header_demo_subtitle": "左侧：结构化对话代理（流程图驱动） | 右侧：实时流程图",
        "header_study_subtitle": "左侧：任务对话与进度 | 右侧：实时 UML 流程图",
        "info_button": "说明",
        "info_title_demo": "界面说明",
        "info_title_study": "调研说明",
        "info_demo_1": "目标：展示结构化对话与流程图之间的联动。",
        "info_demo_2": "左侧：结构化对话面板，展示对话内容与当前状态。",
        "info_demo_3": "右侧：流程图可视化，实时展示路径与状态更新。",
        "info_demo_4": "你可以点击流程图节点进行跳转和聚焦。",
        "info_study_1": "按顺序完成任务。每次只显示一个任务。",
        "info_study_2": "左侧：任务对话与进度。右侧：实时 UML 流程图。",
        "info_study_3": "任务完成后 10 秒自动进入下一个任务。",
        "login_button": "登录",
        "reset_button": "重置对话",
        "translate_button": "English",
        "translate_button_zh": "中文",
        "translate_button_en": "English",
        "not_logged_in": "未登录",
        "login_modal_title": "登录",
        "login_modal_user": "用户名",
        "login_modal_pass": "密码",
        "login_modal_submit": "登录",
        "login_modal_cancel": "取消",
        "study_login_title": "受试者登录",
        "study_login_desc": "请输入研究者提供的用户名和密码。",
        "study_login_submit": "登录",
        "study_info_title": "说明",
        "study_info_flow_title": "流程",
        "study_info_flow_body": "你将按顺序完成所有配置的 UML 任务。到达任意 stop 节点即视为完成当前任务。",
        "study_info_timing_title": "计时",
        "study_info_timing_body": "任务完成后 10 秒将自动进入下一个任务。",
        "study_info_notes_title": "注意事项",
        "study_info_notes_1": "仅使用分配给你的账号",
        "study_info_notes_2": "按顺序完成任务",
        "study_info_notes_3": "研究会记录你的交互操作",
        "structured_agent_title": "结构化代理（流程图驱动）",
        "structured_agent_subtitle": "严格流程约束 • 路径可预测 • 状态可见",
        "current_state": "当前状态",
        "task_progress": "任务进度",
        "study_task_jump_label": "题目切换",
        "study_task_jump_hint": "每题完成后仍会自动进入下一题。你也可以在这里切换到其他题目。",
        "task_target_select_placeholder": "请选择目标节点",
        "task_target_select_hint_pending": "开始作答前，请先用鼠标滚动右侧流程图浏览节点，并在任务进度面板选择你想到达的节点。",
        "task_target_select_hint_ready": "目标节点已选择：{goal}。现在可以开始作答。",
        "task_target_select_hint_missing": "请先在任务进度面板选择目标节点，再开始作答。",
        "task_target_select_label": "目标节点",
        "task_awaiting_login": "等待登录",
        "task_signin_hint": "请登录后开始调研。",
        "flowchart_panel_title": "实时流程图",
        "flowchart_panel_subtitle": "可视化状态与路径",
        "workflow_select_label": "流程选择",
        "workflow_select_placeholder": "选择一个流程",
        "workflow_select_empty": "暂无流程",
        "default_flowchart_title": "流程图",
        "send_button": "发送",
        "structured_input_study_placeholder": "登录后开始...",
        "structured_input_default_placeholder": "请输入您的消息...",
        "structured_input_active_placeholder": "请输入内容...",
        "demo_welcome": "你将开始与结构化代理进行对话。该代理会严格按照流程图推进，并实时更新当前状态。你可以发送消息，观察它如何按既定流程响应。",
        "study_welcome": "请登录后开始调研。系统会一次展示一个 UML 任务。",
        "study_task_loaded_prefix": "任务已加载",
        "study_task_loaded_suffix": "请根据流程图完成任务，到达任意 stop 节点即可完成。",
        "study_task_loading": "正在加载任务...",
        "study_task_wait": "请稍候。",
        "study_no_tasks": "没有可用任务",
        "study_no_tasks_desc": "当前账号没有可用的调研任务。",
        "study_task_in_progress": "进行中",
        "study_task_loading_uml": "正在加载 UML 任务...",
        "study_task_complete_title": "任务 {n} 已完成",
        "study_task_complete_wait": "{n} 秒后进入下一个任务。",
        "study_next_task_button": "立即进入下一任务",
        "study_done_title": "感谢你的参与",
        "study_done_body": "所有任务已完成，你可以关闭页面。",
        "study_all_done_card_title": "所有任务已完成",
        "study_all_done_card_status": "感谢你的参与。",
        "logged_in_as": "已登录：{username}",
        "login_failed": "登录失败：{error}",
        "load_failed": "加载失败：{error}",
        "task_list_failed": "任务列表加载失败：{error}",
        "task_start_failed": "任务启动失败：{error}",
        "task_start_failed_inline": "无法启动任务：{error}",
        "chat_failed": "服务暂时不可用，请稍后重试。",
        "processing_placeholder": "处理中...",
        "confirm_phrase_1": "温馨提示：请确认一下，我们就继续下一步。",
        "confirm_phrase_2": "这一步只需要你的确认，请确认后继续。",
        "confirm_phrase_3": "请确认一下，这样我们就可以继续了。",
        "confirm_phrase_4": "和你确认一下，确认后我们马上继续。",
    },
}


def get_ui_texts_bundle():
    return UI_TEXTS
